version: '3.6'
services:
  memcache:
    image: memcached:latest
  game:
    build:
      './php/'
    volumes:
      - ./game/:/var/www/
    env_file:
      .env
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./game/:/var/www/
      - ./dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    depends_on:
      - game
      - memcache
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: db
networks:
  default:
    external: 
      name: morzo