version: '3.6'
services:
  game:
    build:
      build: './php/'
    volumes:
      - ./game/:/var/www/html/
    env_file:
      .env
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    depends_on:
      - game
networks:
  default:
    external: 
      name: charchat